version: '2'
services:
    widgettest-app:
        image: widgettest
        external_links:
            - widgettest-mongodb:mongodb
        environment:
            - SPRING_PROFILES_ACTIVE=prod
            - SPRING_DATA_MONGODB_URI=mongodb://mongodb:27017
            - SPRING_DATA_MONGODB_DATABASE=widgetTest
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    widgettest-mongodb:
        extends:
            file: mongodb.yml
            service: widgettest-mongodb
