version: '2'
services:
    widgettest-mongodb:
        container_name: widgettest-mongodb
        image: mongo:3.3.5
        ports:
            - "27017:27017"
        # volumes:
        #     - ~/volumes/jhipster/widgetTest/mongodb/:/data/db/
